name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    permissions:
      contents: write
      actions: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
      
    - run: npm ci
    - run: npm run build
    
    - name: Check for changes
      run: |
        set +e
        git diff --quiet
        echo "any_changes=$?" >> "$GITHUB_ENV"
    
    - name: Commit build
      if: ${{ env.any_changes == 1 }}
      run: |
        git config --global user.name 'Github Actions'
        git config --global user.email '<>'
        git add --force dist/*
        git commit -m "Chore: Automatic build"
        git push