# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Publish Package

on:
  release:
    types: [published]

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
      - uses: actions/checkout@v3
      # Code for future NPM compatibility
      #- uses: actions/setup-node@v3
      #  with:
      #    node-version: '16.x'
      #    registry-url: 'https://registry.npmjs.org'
      #    
      #- run: npm ci
      
      #- name: Publish to NPM
      #  run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: ${{ github.repository_owner }}
          
      - run: npm ci
      
      - name: Modify package version
        run: |
          npm version ${{ github.event.release.tag_name }} --no-git-tag-version --allow-same-version
        
      - name: Check for changes
        run: |
          set +e
          git diff --quiet
          echo "any_changes=$?" >> "$GITHUB_ENV"
        
      - name: Commit version if changed
        if: ${{ env.any_changes == 1 }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add package.json
          git commit -m "Chore: Update version to ${{ github.event.release.tag_name }}"
          git push origin HEAD:${{ github.event.release.target_commitish }}
      
      - name: Publish to GitHub Package Registry
        run: |
          sed -i 's+"name": ".*+"name": "@${{ github.repository }}",+gI' ./package.json
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
